# Generated by Django 2.1.7 on 2019-03-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=24)),
                ('contact_name', models.CharField(blank=True, max_length=128, null=True)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('suburb', models.CharField(max_length=128)),
                ('post_code', models.SmallIntegerField(blank=True, null=True)),
                ('state', models.SmallIntegerField(blank=True, choices=[(1, 'New South Wales'), (2, 'Victoria'), (3, 'Queensland'), (4, 'Western Australia'), (5, 'South Australia'), (6, 'Tasmania'), (7, 'Australian Capital Territory'), (8, 'Northern Territory'), (9, 'Norfolk Island'), (10, 'Christmas Island'), (11, 'Australian Antarctic Territory'), (12, 'Cocos (Keeling) Islands'), (13, 'Jervis Bay Territory'), (14, 'Coral Sea Islands'), (15, 'Ashmore and Cartier Islands'), (16, 'Heard Island and McDonald Islands')], null=True)),
            ],
        ),
    ]
