# Generated by Django 2.1.7 on 2019-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='post_code',
            field=models.SmallIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
