# Generated by Django 2.1.7 on 2019-03-19 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_test', '0003_auto_20190319_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='post_code',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
