# Generated by Django 2.1.7 on 2019-03-19 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_test', '0004_auto_20190319_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='post_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
